In [1]:
import os
from bs4 import BeautifulSoup
import pandas as pd
import requests
from requests import get
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
from nltk.tokenize import RegexpTokenizer
from math import log
from math import sqrt
from collections import Counter
from time import sleep
from random import randint
from warnings import warn
from IPython.core.display import clear_output
from time import time
import sklearn
from sklearn.cluster import KMeans

In [2]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\valer\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [3]:
pages = [str(i) for i in range(1,440)]

In [4]:
pages = [str(i) for i in range(1,3)]

In [5]:
# Lists to store the scraped data int
prices = []
locals_ = []
surfaces = []
bathrooms = []
floors = []
descriptions = []

Let's store first 25 houses (those present in the first web page)

In [6]:
# Preparing the monitoring of the loop
start_time = time()
requests = 0

# For every page in the interval 1-4
for page in pages:
    url = ('https://www.immobiliare.it/vendita-case/roma/?criterio=rilevanza&pag=' +page)
    response = get(url)
    # Pause the loop
    sleep(randint(8,15))
    # Monitor the requests
    requests += 1
    elapsed_time = time() - start_time
    print('Request:{}; Frequency: {} requests/s'.format(requests, requests/elapsed_time))
    clear_output(wait = True)
    # Throw a warning for non-200 status codes
    if response.status_code != 200:
        warn('Request: {}; Status code: {}'.format(requests, response.status_code))
    # Break the loop if the number of requests is greater than expected
    if requests > 10000:
        warn('Number of requests was greater than expected.')  
        break
    # Parse the content of the request with BeautifulSoup
    page_html = BeautifulSoup(response.text, 'html.parser')

    # Select all the 50 movie containers from a single page
    house_containers = page_html.find_all('div', class_ = 'listing-item_body--content')
    for house in house_containers:
        house.find('div', class_ = '"lif__item lif__pricing')
        locals_surface_bathrooms = house.findAll('span', class_="text-bold")
        floor = house.findAll('abbr', class_="text-bold im-abbr")
    # If the house has all info that need us (price, locals, surface, bathroom and floor) then extract:
        if len(locals_surface_bathrooms) == 3 :
                      if  len(floor) == 1:

        # The price
                          price = house.find('li', class_="lif__item lif__pricing").text.strip()
                          prices.append(price)

        #the number of locals, surface (m^2), and number of bathrooms
                          local_ = locals_surface_bathrooms[0].text.strip()
                          if '+' in local_:
                              local_ = re.sub('[+]', '', local_)
                          locals_.append(local_)
                          surface = locals_surface_bathrooms[1].text.strip()
                          surfaces.append(surface)
                          bathroom = locals_surface_bathrooms[2].text.strip()
                          if '+' in bathroom:
                              bathroom = re.sub('[+]', '', bathroom)
                          bathrooms.append(bathroom)
                          bathrooms.append(bathroom)
        
        #the number of floor
                          floor = house.find('abbr', class_="text-bold im-abbr").text.strip()
                          floors.append(floor)

        # the description
                          description = house.find('p', class_="descrizione__truncate").text.strip()
                          descriptions.append(description)

NameError: name 're' is not defined

In [7]:
test_df = pd.DataFrame({'price': prices,
                       'locals': locals_,
                       'surface': surfaces,
                       'bathroom': bathrooms,
                       'floor': floors})

In [8]:
test_df

,price,locals,surface,bathroom,floor
0,€ 225.000,2,50,1,"[<abbr class=""text-bold im-abbr"" title=""1"">1 ..."
1,€ 669.000,5,86,2,"[<abbr class=""text-bold im-abbr"" title=""4"">4 ..."
2,€ 500.000,3,89,2,"[<abbr class=""text-bold im-abbr"" title=""3"">3 ..."
3,€ 400.000,3,60,1,"[<abbr class=""text-bold im-abbr"" title=""3"">3 ..."
4,€ 574.000,4,89,2,"[<abbr class=""text-bold im-abbr"" title=""5"">5 ..."
5,€ 300.000,2,46,1,"[<abbr class=""text-bold im-abbr"" title=""4"">4 ..."
6,€ 425.000,3,72,2,"[<abbr class=""text-bold im-abbr"" title=""4"">4 ..."
7,€ 257.000,3,61,1,"[<abbr class=""text-bold im-abbr"" title=""1"">1 ..."
8,€ 657.000,5,87,2,"[<abbr class=""text-bold im-abbr"" title=""5"">5 ..."
9,€ 325.000,2,60,1,"[<abbr class=""text-bold im-abbr"" title=""3"">3 ..."
10,€ 569.000,3,74,2,"[<abbr class=""text-bold im-abbr"" title=""5"">5 ..."
11,€ 175.000,2,52,1,"[<abbr class=""text-bold im-abbr"" title=""1"">1 ..."
12,€ 217.000,2,54,1,"[<abbr class=""text-bold im-abbr"" title=""5"">5 ..."
13,€ 155.000,3,80,1,"[<abbr class=""text-bold im-abbr"" title=""1"">1 ..."
14,€ 1.170.000,5+,300,3,"[<abbr class=""text-bold im-abbr"" title=""1"">1 ..."
15,€ 395.000,5+,130,2,"[<abbr class=""text-bold im-abbr"" title=""1"">1 ..."
16,€ 275.000,3,72,1,"[<abbr class=""text-bold im-abbr"" title=""2"">2 ..."
17,€ 325.000,3,100,2,"[<abbr class=""text-bold im-abbr"" title=""5"">5 ..."
18,€ 1.250.000,5,185,3,"[<abbr class=""text-bold im-abbr"" title=""Piano ..."
19,€ 930.000,5+,150,2,"[<abbr class=""text-bold im-abbr"" title=""3"">3 ..."
20,€ 519.000,4,150,3,"[<abbr class=""text-bold im-abbr"" title=""3"">3 ..."
21,€ 1.350.000,4,137,2,"[<abbr class=""text-bold im-abbr"" title=""4"">4 ..."
22,€ 795.000,5,115,1,"[<abbr class=""text-bold im-abbr"" title=""2"">2 ..."
23,€ 739.000,5,150,2,"[<abbr class=""text-bold im-abbr"" title=""Piano ..."
24,€ 1.680.000,5+,210,2,"[<abbr class=""text-bold im-abbr"" title=""5"">5 ..."
25,€ 239.000,3,87,1,"[<abbr class=""text-bold im-abbr"" title=""Semint..."
26,€ 390.000,3,93,1,"[<abbr class=""text-bold im-abbr"" title=""2"">2 ..."
27,€ 279.000,3,120,1,"[<abbr class=""text-bold im-abbr"" title=""5"">5 ..."
28,€ 235.000,2,56,1,"[<abbr class=""text-bold im-abbr"" title=""4"">4 ..."
29,€ 1.050.000,5+,235,3,"[<abbr class=""text-bold im-abbr"" title=""3"">3 ..."
30,€ 260.000,3,78,2,"[<abbr class=""text-bold im-abbr"" title=""1"">1 ..."
31,€ 620.000,2,65,1,"[<abbr class=""text-bold im-abbr"" title=""3"">3 ..."
32,€ 650.000,4,130,2,"[<abbr class=""text-bold im-abbr"" title=""1"">1 ..."
33,€ 1.600.000,5+,340,3+,"[<abbr class=""text-bold im-abbr"" title=""2"">2 ..."
34,€ 849.000,4,127,1,"[<abbr class=""text-bold im-abbr"" title=""2"">2 ..."
35,€ 950.000,5,170,1,"[<abbr class=""text-bold im-abbr"" title=""3"">3 ..."
36,€ 650.000,5+,193,3,"[<abbr class=""text-bold im-abbr"" title=""4"">4 ..."
37,€ 800.000,3,125,2,"[<abbr class=""text-bold im-abbr"" title=""5"">5 ..."
38,€ 1.050.000,5+,290,2,"[<abbr class=""text-bold im-abbr"" title=""Piano ..."
39,€ 229.000,2,70,1,"[<abbr class=""text-bold im-abbr"" title=""5"">5 ..."
40,€ 800.000,5+,220,3,"[<abbr class=""text-bold im-abbr"" title=""4"">4 ..."
41,€ 450.000,4,166,2,"[<abbr class=""text-bold im-abbr"" title=""4"">4 ..."

Let's to cleaning houses description

In [22]:
def clening_description(description):  # use all the techniques to remove unwanted items from words
    
    tokenizer = RegexpTokenizer(r'\w+')
    ps = PorterStemmer()
    # Remove "\\n" and replace with a space
    description = description.replace("\\n", " ")
    # Convert everything to lowercase
    description = description.lower()
    # Removing punctuation
    description = tokenizer.tokenize(description)
    # Stemming
    description = [ps.stem(word) for word in description]
    # Removing stopwords
    description = [word for word in description if word not in stopwords.words('italian')]
    # No integers
    description = [x for x in description if not (x.isdigit() or x[0].isdigit())]
    return description

In [13]:
cleaned_descriptions = []
for description in descriptions:
    cleaned_description = clening_description(description)
    cleaned_descriptions.append(cleaned_description)

In [14]:
corpus = [y for x in cleaned_descriptions for y in x]

#all words present in all descriptions

In [15]:
count_corpus = Counter(corpus)
count_corpus= dict(count_corpus.most_common())

final_dict = {str(i+1):x for i,x in enumerate(count_corpus)}
final_dict_inv = {str(x):(i+1) for i,x in enumerate(count_corpus)}

In [16]:
indx = {}
for n,document in enumerate(cleaned_descriptions):
    new_document = []
    for word in document:
        new_document.append(final_dict_inv[str(word)])
    indx[str(n+1)] = new_document 
    
inv_indx = {str(i):[] for i in list(final_dict.keys())}
for word in list(final_dict.keys()):
    for i in range(len(indx)):
        if int(word) in indx[str(i+1)]:
            inv_indx[word].append(i+1)

In [17]:
houses_count= len(test_df)

In [18]:
inv_indx_cosine = {i:[] for i in list(final_dict.keys())}
for word in list(final_dict.keys()):
    for i,l in enumerate(list(indx.values())):
        if int(word) in l:
            tf = l.count(int(word))/len(l)
            id_f = log(houses_count/len(inv_indx[word]))
            inv_indx_cosine[word].append((i+1,tf*id_f))

Let's to deal with our inv_indx_cosine to build tf-idf matrix

In [19]:
converting = [(k, *t) for k, v in inv_indx_cosine.items() for t in v ]

In [20]:
test = pd.DataFrame(converting, columns=['Word', 'Document', 'Tf-Idf'])

In [22]:
matrix_tfidf = test.pivot_table(index = 'Document', columns = 'Word', values='Tf-Idf', fill_value = 0)

In [23]:
matrix_tfidf.head()

Word,1,10,100,101,102,103,104,105,106,107,...,90,91,92,93,94,95,96,97,98,99
Document,,,,,,,,,,,,,,,,,,,,,
1,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,0.010674,0.024497,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,0.011341,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.076323,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,0.011341,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.076323,0.076323,0.076323,0.076323,0.000000,0.000000,0.000000,0.000000,0.000000
5,0.024194,0.000000,0.081412,0.081412,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.209033,0.081412,0.081412,0.081412,0.081412

In [26]:
cluster = sklearn.cluster.KMeans(n_clusters=8, init='k-means++', n_init=10, max_iter=300, tol=0.0001, precompute_distances='auto', verbose=0, random_state=None, copy_x=True, n_jobs=1)

In [27]:
# k means determine k for first matrix
distortions = []
K = range(1,10)
for k in K:
    kmeanModel = KMeans(n_clusters=k).fit(test_df)
    kmeanModel.fit(test_df)
    distortions.append(sum(np.min(cdist(test_df, kmeanModel.cluster_centers_, 'euclidean'), axis=1)) / test_df.shape[0])

# Plot the elbow
plt.plot(K, distortions, 'bx-')
plt.xlabel('k')
plt.ylabel('Distortion')
plt.title('The Elbow Method showing the optimal k')
plt.show()

ValueError: setting an array element with a sequence.